# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-22 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comics', '0002_auto_20180220_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='excelSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.FileField(upload_to='')),
            ],
        ),
    ]
